dependencies:
- name: address-hub-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.29
- name: configuration-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.34
- name: crm-admin-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 2.5.4
- name: crm-backend-nodejs
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.56
- name: crm-backend-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.26
- name: crm-common
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.1
- name: event-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.75
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: field-definitions-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.111
- name: meter-data-hub-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.19
- name: organisation-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.42
- name: payment-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.24
- name: processing-path-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.149
- name: product-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.120
- name: registry-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.6
- name: session-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.15
- name: template-definition-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.43
- name: user-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.212
