dependencies:
- name: address-hub-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.12
- name: configuration-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.18
- name: crm-admin-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.16
- name: crm-backend-nodejs
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.44
- name: crm-backend-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.26
- name: crm-common
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.1
- name: event-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.33
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: field-definitions-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.93
- name: meter-data-hub-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.7
- name: organisation-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.31
- name: payment-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.14
- name: processing-path-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.51
- name: product-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.84
- name: registry-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.5
- name: session-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.5
- name: template-definition-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.31
- name: user-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.85
