dependencies:
- name: address-hub-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.11
- name: crm-backend-nodejs
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.28
- name: crm-backend-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.15
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: field-definitions-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.70
- name: meter-data-hub-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.2
- name: payment-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.2
- name: processing-path-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.13
- name: product-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.64
- name: registry-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.2
