dependencies:
- name: address-hub-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.11
- name: configuration-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.3
- name: crm-backend-nodejs
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.36
- name: crm-backend-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.16
- name: crm-common
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.1
- name: event-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.4
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: field-definitions-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.76
- name: meter-data-hub-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.2
- name: organisation-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.13
- name: payment-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.4
- name: processing-path-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.18
- name: product-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.76
- name: registry-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.2
- name: template-definition-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.23
- name: user-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.27
