dependencies:
- name: address-hub-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.11
- name: configuration-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.18
- name: crm-backend-nodejs
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.42
- name: crm-backend-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.20
- name: crm-common
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.1
- name: event-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.17
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: field-definitions-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.87
- name: meter-data-hub-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.6
- name: organisation-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.26
- name: payment-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.12
- name: processing-path-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.34
- name: product-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.82
- name: registry-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.3
- name: session-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.3
- name: template-definition-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.28
- name: user-management-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.65
